name: cubeflow
channels:
    - anaconda
    - pytorch
dependencies:
    - python
    - pip
    - pytorch
    - torchvision
    - numpy
    - pandas
    - psutil
    - plotly
    - scikit-learn=0.22.0
    - pip:
        - coolname
        - streamlit
        - matplotlib
        - wandb
        - slackclient
        - fastparquet
        - torchsummary
