name: cubeflow
channels:
    - anaconda
    # - pytorch
dependencies:
    - python=3.7
    # - python
    - pip
    # - pytorch=1.4.0
    # - torchvision=0.4.2
    # - cudatoolkit=10.1
    - h5py
    - numpy
    - pandas
    # - scikit-learn">=0.22, <=0.22"
    - psutil
    - plotly
    - pip:
        - bunch
        - coolname
        - streamlit
        - matplotlib
        - wandb
        - torchsummary
        - torch-lr-finder
        - pytorch-lightning
        - snakeviz
        - paramiko
        - scp
        - pyyaml
        - slackclient
        - fastparquet
