name: cubeflow
channels:
    - anaconda
dependencies:
    - pip
    - h5py
    - numpy
    - pandas
    - scikit-learn
    - tensorflow-gpu
    - psutil
    - pydot
    - pip:
        - bunch
        - comet_ml
        - coolname
        - graphviz
        - neptune-client
        - neptune_tensorboard
        - streamlit
