name: cubeflow
channels:
    - anaconda
    # - pytorch
dependencies:
    - python=3.7
    - pip
    - pytorch=1.3.0
    - torchvision
    - cudatoolkit
    - h5py
    - numpy
    - pandas
    # - scikit-learn">=0.22, <=0.22"
    - psutil
    - plotly
    - pip:
        - bunch
        - coolname
        - streamlit
        - matplotlib
        - wandb
        - torchsummary
        - torch-lr-finder
        - pytorch-lightning

