name: cubeflow
channels:
    - anaconda
    - pytorch
dependencies:
    - pip
    - h5py
    - jupyter
    - numpy
    - pandas
    - scikit-learn
    - pytorch
    - torchvision
    - cudatoolkit=10.1
    - psutil
    - plotly
    - pip:
        - bunch
        - coolname
        - streamlit
        - matplotlib
        - wandb
