name: cubeflow
channels:
    - anaconda
dependencies:
    - pip
    - h5py
    - numpy
    - pandas
    - scikit-learn
    - tensorflow-gpu
    - psutil
    - pip:
        - bunch
        - coolname
        - streamlit
        - matplotlib
